#include "runAction.h"

runAction::runAction()
{}

runAction::~runAction()
{}

//TODO:
/*
  Make geometry that has two SDs, one at each end. Do with both PBW04 LAr.
  Make histograms:
  2D Histograms of the photons detected by SD
  Timing Histogram
  Slow/Fast Turn on scintillation
  Set refractive index all the way to red, use constant.
  Plot angle of photon for both Scinitillation and Cerenkov.
  Plot cos of angle.
*/

void runAction::BeginOfRunAction(const G4Run*)
{
    G4AnalysisManager *man = G4AnalysisManager::Instance();
    man->SetVerboseLevel(1);
    man->OpenFile("hits.root");

    //Histogram plotting number of photons detected by SD
    //Since its the first histogram, ID = 0
    man->CreateH1("SDphotonHits", "Number of Photons", 10, 0, 10);
    man->SetH1XAxisTitle(0, "Event ID");
    man->SetH1YAxisTitle(0, "Number of Photons");

    //Histogram plotting energy of photon detected by SD
    //ID = 1
    man->CreateH1("SDphotonWavelength", "Photon Wavelength", 200, 100, 1000);
    man->SetH1YAxisTitle(1, "Number of Photons");
    man->SetH1XAxisTitle(1, "Photon Wavelength (nm)");

    //Histogram plotting number of photons generated by Cerenkov
    //ID = 2
    man->CreateH1("cerenkovPhotonQuantity", "Number of Cerenkov Photons", 10, 0, 10);
    man->SetH1XAxisTitle(2, "Event ID");
    man->SetH1YAxisTitle(2, "Number of Photons");

    //Histogram plotting the Wavelength of photons generated by Cerenkov radiation
    //ID = 3
    man->CreateH1("cerenkovPhotonWavelength","Cerenkov Photon Wavelength", 200, 100, 1000);
    man->SetH1YAxisTitle(3, "Number of Photons");
    man->SetH1XAxisTitle(3, "Photon Wavelength (nm)");


    //Histogram plotting the number of photons generated by scintillation
    //ID = 5
    man->CreateH1("scintillationPhotonQuantity", "Number of Scintillation Photons", 10, 0 ,10);
    man->SetH1XAxisTitle(4, "Event ID");
    man->SetH1YAxisTitle(4, "Number of Photons");

    //Histogram plotting the wavelength of photons generated by Scintillation
    //ID = 6
    man->CreateH1("scintillationPhotonWavelength", "Scintillation Photon Wavelength", 200, 100, 170);
    man->SetH1XAxisTitle(5, "Photon Wavelength (nm)");
    man->SetH1YAxisTitle(5, "Number of Photons");

    //Histogram plotting the Z-position of Cerenkov photons as they are generated
    man->CreateH1("cerenkovZPosition", "Photon Z Position", 100, 0 ,100);
    man->SetH1XAxisTitle(6, "Photon Position(mm)");
    man->SetH1YAxisTitle(6, "Number of Photons");

    //Histogram plotting the Wavelength of the photons hitting SD1
    man->CreateH1("SD1wavelengths", "Photon Wavelengths from SD1", 200, 0, 1000);
    man->SetH1XAxisTitle(7, "Photon Wavelength(nm)");
    man->SetH1YAxisTitle(7, "Number of Photons");

    //Histogram plotting the Wavelength of the photons hitting SD2
    man->CreateH1("SD2wavelengths", "Photon Wavelengths from SD2", 200, 0, 1000);
    man->SetH1XAxisTitle(8, "Photon Wavelength(nm)");
    man->SetH1YAxisTitle(8, "Number of Photons");

    //Histogram plotting the angle of emission of Cerenkov photons
    man->CreateH1("cerenkovAngleOfEmission", "Photon angle of Emission", 200, 0, 1000);
    man->SetH1XAxisTitle(9, "Photon angle of Emission");
    man->SetH1YAxisTitle(9, "Number of Photons");

    //Histogram plotting the angle of emission of Scintillation photons
    man->CreateH1("scintillationAngleOfEmission", "Photon angle of Emission", 200, 0 ,1000);
    man->SetH1XAxisTitle(10, "Photon angle of Emission");
    man->SetH1YAxisTitle(10, "Number of  Photons");

    //2D Histogram plotting the XY position of Cerenkov radiation as it is detected by SD1
    //ID = 0
    man->CreateH2("cerenkovPhotonXYSD1", "Cerenkov Photon Position", 100, -100, 100, 100,-100, 100);
    man->SetH2XAxisTitle(0, "Photon Position X (mm)");
    man->SetH2YAxisTitle(0, "Photon Position Y (mm)");
    man->SetH2ZAxisTitle(0, "Number Of Photons");

    //2D Histogram plotting the XY position of Scintillation Radiation as it is detected by SD1
    //ID = 1
    man->CreateH2("scintillationPhotonXYSD1", "Scintillation Photon Position", 100, -100, 100, 100, -100,100);
    man->SetH2XAxisTitle(1, "Photon Position X(mm)");
    man->SetH2YAxisTitle(1, "Photon Position Y(mm)");
    man->SetH2ZAxisTitle(1, "Photon Position Z(mm)");

    //2D Histogram plotting the XY position of Cerenkov Radiation as it is detected by SD2
    //ID = 2
    man->CreateH2("cerenkovPhotonXYSD2", "Cerenkov Photon Position", 100, -100, 100, 100, -100, 100);
    man->SetH2XAxisTitle(2, "Photon Position X(mm)");
    man->SetH2YAxisTitle(2, "Photon Position Y(mm)");
    man->SetH2ZAxisTitle(2, "Photon Position Z(mm)");

    //2D Histogram plotting the XY position of Scintillation Radiation as it is detected by SD2
    //ID = 3
    man->CreateH2("scintillationPhotonXYSD2", "Scintillation Photon Position", 100, -100, 100, 100, -100, 100);
    man->SetH2XAxisTitle(3, "Photon Position X(mm)");
    man->SetH2YAxisTitle(3, "Photon Position Y(mm)");
    man->SetH2ZAxisTitle(3, "Photon Position Z(mm)");




}

void runAction::EndOfRunAction(const G4Run*)
{
    G4AnalysisManager *man = G4AnalysisManager::Instance();

    man->Write();
    man->CloseFile();
}
