#include "runAction.h"

runAction::runAction()
{}

runAction::~runAction()
{}

void runAction::BeginOfRunAction(const G4Run*)
{
    G4AnalysisManager *man = G4AnalysisManager::Instance();
    man->SetVerboseLevel(1);
    man->OpenFile("hits.root");

    //Histogram plotting number of photons detected by SD
    //Since its the first histogram, ID = 0
    man->CreateH1("SDphotonHits", "Number of Photons", 10, 0, 10);
    man->SetH1XAxisTitle(0, "Event ID");
    man->SetH1YAxisTitle(0, "Number of Photons");

    //Histogram plotting energy of photon detected by SD
    //ID = 1
    man->CreateH1("SDphotonWavelength", "Photon Wavelength", 30000, 100, 170);
    man->SetH1YAxisTitle(1, "Number of Photons");
    man->SetH1XAxisTitle(1, "Photon Wavelength (nm)");

    //Histogram plotting number of photons generated by Cerenkov
    //ID = 2
    man->CreateH1("cerenkovPhotonQuantity", "Number of Cerenkov Photons", 10, 0, 10);
    man->SetH1XAxisTitle(2, "Event ID");
    man->SetH1YAxisTitle(2, "Number of Photons");

    //Histogram plotting the Wavelength of photons generated by Cerenkov radiation
    //ID = 3
    man->CreateH1("cerenkovPhotonWavelength","Cerenkov Photon Wavelength", 30000, 100, 170);
    man->SetH1YAxisTitle(3, "Number of Photons");
    man->SetH1XAxisTitle(3, "Photon Wavelength (nm)");

    //Histogram plotting the Z position of Cerenkov radiation as it is detected by SD
    //ID = 4
    man->CreateH1("cerenkovZPosition", "Photon Z Position", 10, 0, 100);
    man->SetH1XAxisTitle(4, "Photon Position");
    man->SetH1YAxisTitle(4, "Number Of Photons");

    //Histogram plotting the number of photons generated by scintillation
    //ID = 5
    man->CreateH1("scintillationPhotonQuantity", "Number of Scintillation Photons", 10, 0 ,10);
    man->SetH1XAxisTitle(5, "Event ID");
    man->SetH1YAxisTitle(5, "Number of Photons");

    //Histogram plotting the wavelength of photons generated by Scintillation
    //ID = 6
    man->CreateH1("scintillationPhotonWavelength", "Scintillation Photon Wavelength", 30000, 100, 170);
    man->SetH1XAxisTitle(6, "Photon Wavelength (nm)");
    man->SetH1YAxisTitle(6, "Number of Photons");

    //Ntuple plotting the number of Cerenkov photons detected by SD
    //ID = 0
    man->CreateNtuple("cerenkovPhotonNumber", "Number of Cerenkov Photons");
    man->CreateNtupleDColumn("cP");
    man->FinishNtuple(0);

    //Ntuple plotting the number of Scintillation photons detected by SD
    //ID = 1
    man->CreateNtuple("scintillationPhotonNumber", "Number of Cerenkov Photons");
    man->CreateNtupleDColumn("sP");
    man->FinishNtuple(1);



}

void runAction::EndOfRunAction(const G4Run*)
{
    G4AnalysisManager *man = G4AnalysisManager::Instance();

    man->Write();
    man->CloseFile();
}
